name: "Lint PR"

on:
  pull_request:
    branches: 
      - develop
      - release/*
      - hotfix/*
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            refactor
            perf
            chore
            revert
          subjectPattern: ^.+[A-Z]{1}[A-Z0-9]{1,4}-[0-9]{1,6}.*$
          subjectPatternError: |
            The subject "{subject}" didn't match the configured pattern. Please ensure 
            that the subject refers to a JIRA ticket.
