name: Build and release Next.js web application
on: push
jobs:
  release-project:
    name: Release static site to GitHub Releases
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Create GitHub Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
         tag_name: v${{ github.run_number }}
         release_name: Release V${{ github.run_number }}
  changelog :
    name: Update changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
  build-project:
    name: Build Next.js application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Upload static website
        uses: actions/upload-artifact@v2
        with:
          name: static-site
          path: out/
